version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eia_postgres
    restart: always

    environment:
      POSTGRES_USER: eia_user
      POSTGRES_PASSWORD: eia_password
      POSTGRES_DB: eia_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
